# Generated by cpp11: do not edit by hand

is_compact_seq <- function(x) {
  .Call(`_cheapr_is_compact_seq`, x)
}

compact_seq_data <- function(x) {
  .Call(`_cheapr_compact_seq_data`, x)
}

cpp_set_rm_attributes <- function(x) {
  .Call(`_cheapr_cpp_set_rm_attributes`, x)
}

cpp_set_add_attr <- function(x, which, value) {
  .Call(`_cheapr_cpp_set_add_attr`, x, which, value)
}

cpp_set_rm_attr <- function(x, which) {
  .Call(`_cheapr_cpp_set_rm_attr`, x, which)
}

cpp_set_add_attributes <- function(x, attributes, add) {
  .Call(`_cheapr_cpp_set_add_attributes`, x, attributes, add)
}

cpp_gcd2 <- function(x, y, tol, na_rm) {
  .Call(`_cheapr_cpp_gcd2`, x, y, tol, na_rm)
}

cpp_lcm2 <- function(x, y, tol, na_rm) {
  .Call(`_cheapr_cpp_lcm2`, x, y, tol, na_rm)
}

cpp_gcd <- function(x, tol, na_rm, break_early, round) {
  .Call(`_cheapr_cpp_gcd`, x, tol, na_rm, break_early, round)
}

cpp_lcm <- function(x, tol, na_rm) {
  .Call(`_cheapr_cpp_lcm`, x, tol, na_rm)
}

cpp_gcd2_vectorised <- function(x, y, tol, na_rm) {
  .Call(`_cheapr_cpp_gcd2_vectorised`, x, y, tol, na_rm)
}

cpp_lcm2_vectorised <- function(x, y, tol, na_rm) {
  .Call(`_cheapr_cpp_lcm2_vectorised`, x, y, tol, na_rm)
}

cpp_int64_to_int <- function(x) {
  .Call(`_cheapr_cpp_int64_to_int`, x)
}

cpp_int64_to_double <- function(x) {
  .Call(`_cheapr_cpp_int64_to_double`, x)
}

cpp_int64_to_numeric <- function(x) {
  .Call(`_cheapr_cpp_int64_to_numeric`, x)
}

cpp_numeric_to_int64 <- function(x) {
  .Call(`_cheapr_cpp_numeric_to_int64`, x)
}

cpp_format_numeric_as_int64 <- function(x) {
  .Call(`_cheapr_cpp_format_numeric_as_int64`, x)
}

cpp_lag <- function(x, k, fill, set, recursive) {
  .Call(`_cheapr_cpp_lag`, x, k, fill, set, recursive)
}

cpp_lag2 <- function(x, lag, order, run_lengths, fill, recursive) {
  .Call(`_cheapr_cpp_lag2`, x, lag, order, run_lengths, fill, recursive)
}

cpp_r_unnested_length <- function(x) {
  .Call(`_cheapr_cpp_r_unnested_length`, x)
}

cpp_lengths <- function(x, names) {
  .Call(`_cheapr_cpp_lengths`, x, names)
}

cpp_new_list <- function(size, default_value) {
  .Call(`_cheapr_cpp_new_list`, size, default_value)
}

cpp_drop_null <- function(l, always_shallow_copy) {
  .Call(`_cheapr_cpp_drop_null`, l, always_shallow_copy)
}

cpp_list_as_df <- function(x) {
  .Call(`_cheapr_cpp_list_as_df`, x)
}

cpp_num_na <- function(x, recursive) {
  .Call(`_cheapr_cpp_num_na`, x, recursive)
}

cpp_any_na <- function(x, recursive) {
  .Call(`_cheapr_cpp_any_na`, x, recursive)
}

cpp_all_na <- function(x, return_true_on_empty, recursive) {
  .Call(`_cheapr_cpp_all_na`, x, return_true_on_empty, recursive)
}

cpp_is_na <- function(x) {
  .Call(`_cheapr_cpp_is_na`, x)
}

cpp_df_row_na_counts <- function(x) {
  .Call(`_cheapr_cpp_df_row_na_counts`, x)
}

cpp_df_col_na_counts <- function(x) {
  .Call(`_cheapr_cpp_df_col_na_counts`, x)
}

cpp_col_any_na <- function(x, names) {
  .Call(`_cheapr_cpp_col_any_na`, x, names)
}

cpp_col_all_na <- function(x, names) {
  .Call(`_cheapr_cpp_col_all_na`, x, names)
}

cpp_matrix_row_na_counts <- function(x) {
  .Call(`_cheapr_cpp_matrix_row_na_counts`, x)
}

cpp_matrix_col_na_counts <- function(x) {
  .Call(`_cheapr_cpp_matrix_col_na_counts`, x)
}

cpp_row_na_counts <- function(x, names) {
  .Call(`_cheapr_cpp_row_na_counts`, x, names)
}

cpp_col_na_counts <- function(x, names) {
  .Call(`_cheapr_cpp_col_na_counts`, x, names)
}

cpp_count_val <- function(x, value, recursive) {
  .Call(`_cheapr_cpp_count_val`, x, value, recursive)
}

cpp_val_replace <- function(x, value, replace, recursive) {
  .Call(`_cheapr_cpp_val_replace`, x, value, replace, recursive)
}

cpp_val_set_replace <- function(x, value, replace, recursive) {
  .Call(`_cheapr_cpp_val_set_replace`, x, value, replace, recursive)
}

cpp_loc_set_replace <- function(x, where, what) {
  .Call(`_cheapr_cpp_loc_set_replace`, x, where, what)
}

cpp_int_sequence <- function(size, from, by) {
  .Call(`_cheapr_cpp_int_sequence`, size, from, by)
}

cpp_dbl_sequence <- function(size, from, by) {
  .Call(`_cheapr_cpp_dbl_sequence`, size, from, by)
}

cpp_sequence <- function(size, from, by) {
  .Call(`_cheapr_cpp_sequence`, size, from, by)
}

cpp_window_sequence <- function(size, k, partial, ascending) {
  .Call(`_cheapr_cpp_window_sequence`, size, k, partial, ascending)
}

cpp_lag_sequence <- function(size, k, partial) {
  .Call(`_cheapr_cpp_lag_sequence`, size, k, partial)
}

cpp_lead_sequence <- function(size, k, partial) {
  .Call(`_cheapr_cpp_lead_sequence`, size, k, partial)
}

cpp_sequence_id <- function(size) {
  .Call(`_cheapr_cpp_sequence_id`, size)
}

cpp_set_abs <- function(x) {
  .Call(`_cheapr_cpp_set_abs`, x)
}

cpp_set_floor <- function(x) {
  .Call(`_cheapr_cpp_set_floor`, x)
}

cpp_set_ceiling <- function(x) {
  .Call(`_cheapr_cpp_set_ceiling`, x)
}

cpp_set_trunc <- function(x) {
  .Call(`_cheapr_cpp_set_trunc`, x)
}

cpp_set_change_sign <- function(x) {
  .Call(`_cheapr_cpp_set_change_sign`, x)
}

cpp_set_exp <- function(x) {
  .Call(`_cheapr_cpp_set_exp`, x)
}

cpp_set_sqrt <- function(x) {
  .Call(`_cheapr_cpp_set_sqrt`, x)
}

cpp_set_add <- function(x, y) {
  .Call(`_cheapr_cpp_set_add`, x, y)
}

cpp_set_subtract <- function(x, y) {
  .Call(`_cheapr_cpp_set_subtract`, x, y)
}

cpp_set_multiply <- function(x, y) {
  .Call(`_cheapr_cpp_set_multiply`, x, y)
}

cpp_set_divide <- function(x, y) {
  .Call(`_cheapr_cpp_set_divide`, x, y)
}

cpp_set_pow <- function(x, y) {
  .Call(`_cheapr_cpp_set_pow`, x, y)
}

cpp_set_log <- function(x, base) {
  .Call(`_cheapr_cpp_set_log`, x, base)
}

cpp_set_round <- function(x, digits) {
  .Call(`_cheapr_cpp_set_round`, x, digits)
}

cpp_sset_range <- function(x, from, to, by) {
  .Call(`_cheapr_cpp_sset_range`, x, from, to, by)
}

cpp_sset_df <- function(x, indices) {
  .Call(`_cheapr_cpp_sset_df`, x, indices)
}

cpp_vec_length <- function(x) {
  .Call(`_cheapr_cpp_vec_length`, x)
}

r_copy <- function(x) {
  .Call(`_cheapr_r_copy`, x)
}

var_sum_squared_diff <- function(x, mu) {
  .Call(`_cheapr_var_sum_squared_diff`, x, mu)
}

cpp_bin <- function(x, breaks, codes, right, include_lowest, include_oob) {
  .Call(`_cheapr_cpp_bin`, x, breaks, codes, right, include_lowest, include_oob)
}

cpp_rev <- function(x, set) {
  .Call(`_cheapr_cpp_rev`, x, set)
}

cpp_if_else <- function(condition, yes, no, na) {
  .Call(`_cheapr_cpp_if_else`, condition, yes, no, na)
}

cpp_lgl_count <- function(x) {
  .Call(`_cheapr_cpp_lgl_count`, x)
}

cpp_set_copy_elements <- function(source, target) {
  invisible(.Call(`_cheapr_cpp_set_copy_elements`, source, target))
}

cpp_set_or <- function(x, y) {
  .Call(`_cheapr_cpp_set_or`, x, y)
}

cpp_which_ <- function(x, invert) {
  .Call(`_cheapr_cpp_which_`, x, invert)
}

cpp_which_val <- function(x, value, invert) {
  .Call(`_cheapr_cpp_which_val`, x, value, invert)
}

cpp_which_na <- function(x) {
  .Call(`_cheapr_cpp_which_na`, x)
}

cpp_which_not_na <- function(x) {
  .Call(`_cheapr_cpp_which_not_na`, x)
}

cpp_lgl_locs <- function(x, n_true, n_false, include_true, include_false, include_na) {
  .Call(`_cheapr_cpp_lgl_locs`, x, n_true, n_false, include_true, include_false, include_na)
}
