# Generated by cpp11: do not edit by hand

cpp_gcd2 <- function(x, y, tol, na_rm) {
  .Call(`_cheapr_cpp_gcd2`, x, y, tol, na_rm)
}

cpp_lcm2 <- function(x, y, tol, na_rm) {
  .Call(`_cheapr_cpp_lcm2`, x, y, tol, na_rm)
}

cpp_gcd <- function(x, tol, na_rm, break_early, round) {
  .Call(`_cheapr_cpp_gcd`, x, tol, na_rm, break_early, round)
}

cpp_lcm <- function(x, tol, na_rm) {
  .Call(`_cheapr_cpp_lcm`, x, tol, na_rm)
}

cpp_gcd2_vectorised <- function(x, y, tol, na_rm) {
  .Call(`_cheapr_cpp_gcd2_vectorised`, x, y, tol, na_rm)
}

cpp_lcm2_vectorised <- function(x, y, tol, na_rm) {
  .Call(`_cheapr_cpp_lcm2_vectorised`, x, y, tol, na_rm)
}

cpp_num_na <- function(x, recursive) {
  .Call(`_cheapr_cpp_num_na`, x, recursive)
}

cpp_any_na <- function(x, recursive) {
  .Call(`_cheapr_cpp_any_na`, x, recursive)
}

cpp_all_na <- function(x, return_true_on_empty, recursive) {
  .Call(`_cheapr_cpp_all_na`, x, return_true_on_empty, recursive)
}

cpp_which_na <- function(x) {
  .Call(`_cheapr_cpp_which_na`, x)
}

cpp_which_not_na <- function(x) {
  .Call(`_cheapr_cpp_which_not_na`, x)
}

cpp_is_na <- function(x) {
  .Call(`_cheapr_cpp_is_na`, x)
}

cpp_row_na_counts <- function(x) {
  .Call(`_cheapr_cpp_row_na_counts`, x)
}

cpp_col_na_counts <- function(x) {
  .Call(`_cheapr_cpp_col_na_counts`, x)
}

cpp_missing_row <- function(x, threshold, threshold_is_prop) {
  .Call(`_cheapr_cpp_missing_row`, x, threshold, threshold_is_prop)
}

cpp_missing_col <- function(x, threshold, threshold_is_prop) {
  .Call(`_cheapr_cpp_missing_col`, x, threshold, threshold_is_prop)
}

cpp_matrix_row_na_counts <- function(x) {
  .Call(`_cheapr_cpp_matrix_row_na_counts`, x)
}

cpp_matrix_col_na_counts <- function(x) {
  .Call(`_cheapr_cpp_matrix_col_na_counts`, x)
}

cpp_matrix_missing_row <- function(x, threshold, threshold_is_prop) {
  .Call(`_cheapr_cpp_matrix_missing_row`, x, threshold, threshold_is_prop)
}

cpp_matrix_missing_col <- function(x, threshold, threshold_is_prop) {
  .Call(`_cheapr_cpp_matrix_missing_col`, x, threshold, threshold_is_prop)
}

cpp_int_sequence <- function(size, from, by) {
  .Call(`_cheapr_cpp_int_sequence`, size, from, by)
}

cpp_dbl_sequence <- function(size, from, by) {
  .Call(`_cheapr_cpp_dbl_sequence`, size, from, by)
}

cpp_window_sequence <- function(size, k, partial, ascending) {
  .Call(`_cheapr_cpp_window_sequence`, size, k, partial, ascending)
}

cpp_lag_sequence <- function(size, k, partial) {
  .Call(`_cheapr_cpp_lag_sequence`, size, k, partial)
}

cpp_lead_sequence <- function(size, k, partial) {
  .Call(`_cheapr_cpp_lead_sequence`, size, k, partial)
}

cpp_vec_length <- function(x) {
  .Call(`_cheapr_cpp_vec_length`, x)
}

cpp_r_unnested_length <- function(x) {
  .Call(`_cheapr_cpp_r_unnested_length`, x)
}

cpp_lengths <- function(x) {
  .Call(`_cheapr_cpp_lengths`, x)
}

cpp_new_list <- function(size, default_value) {
  .Call(`_cheapr_cpp_new_list`, size, default_value)
}

cpp_list_rm_null <- function(l) {
  .Call(`_cheapr_cpp_list_rm_null`, l)
}

cpp_which_ <- function(x, invert) {
  .Call(`_cheapr_cpp_which_`, x, invert)
}
