# Generated by cpp11: do not edit by hand

cpp_set_rm_attributes <- function(x) {
  .Call(`_cheapr_cpp_set_rm_attributes`, x)
}

cpp_set_add_attr <- function(x, which, value) {
  .Call(`_cheapr_cpp_set_add_attr`, x, which, value)
}

cpp_set_rm_attr <- function(x, which) {
  .Call(`_cheapr_cpp_set_rm_attr`, x, which)
}

cpp_set_add_attributes <- function(x, attributes, add) {
  .Call(`_cheapr_cpp_set_add_attributes`, x, attributes, add)
}

cpp_gcd2 <- function(x, y, tol, na_rm) {
  .Call(`_cheapr_cpp_gcd2`, x, y, tol, na_rm)
}

cpp_lcm2 <- function(x, y, tol, na_rm) {
  .Call(`_cheapr_cpp_lcm2`, x, y, tol, na_rm)
}

cpp_gcd <- function(x, tol, na_rm, break_early, round) {
  .Call(`_cheapr_cpp_gcd`, x, tol, na_rm, break_early, round)
}

cpp_lcm <- function(x, tol, na_rm) {
  .Call(`_cheapr_cpp_lcm`, x, tol, na_rm)
}

cpp_gcd2_vectorised <- function(x, y, tol, na_rm) {
  .Call(`_cheapr_cpp_gcd2_vectorised`, x, y, tol, na_rm)
}

cpp_lcm2_vectorised <- function(x, y, tol, na_rm) {
  .Call(`_cheapr_cpp_lcm2_vectorised`, x, y, tol, na_rm)
}

cpp_lag <- function(x, k, fill, set, recursive) {
  .Call(`_cheapr_cpp_lag`, x, k, fill, set, recursive)
}

cpp_num_na <- function(x, recursive) {
  .Call(`_cheapr_cpp_num_na`, x, recursive)
}

cpp_any_na <- function(x, recursive) {
  .Call(`_cheapr_cpp_any_na`, x, recursive)
}

cpp_all_na <- function(x, return_true_on_empty, recursive) {
  .Call(`_cheapr_cpp_all_na`, x, return_true_on_empty, recursive)
}

cpp_is_na <- function(x) {
  .Call(`_cheapr_cpp_is_na`, x)
}

cpp_which_na <- function(x) {
  .Call(`_cheapr_cpp_which_na`, x)
}

cpp_which_not_na <- function(x) {
  .Call(`_cheapr_cpp_which_not_na`, x)
}

cpp_row_na_counts <- function(x) {
  .Call(`_cheapr_cpp_row_na_counts`, x)
}

cpp_col_na_counts <- function(x) {
  .Call(`_cheapr_cpp_col_na_counts`, x)
}

cpp_missing_row <- function(x, threshold, threshold_is_prop) {
  .Call(`_cheapr_cpp_missing_row`, x, threshold, threshold_is_prop)
}

cpp_missing_col <- function(x, threshold, threshold_is_prop) {
  .Call(`_cheapr_cpp_missing_col`, x, threshold, threshold_is_prop)
}

cpp_matrix_row_na_counts <- function(x) {
  .Call(`_cheapr_cpp_matrix_row_na_counts`, x)
}

cpp_matrix_col_na_counts <- function(x) {
  .Call(`_cheapr_cpp_matrix_col_na_counts`, x)
}

cpp_matrix_missing_row <- function(x, threshold, threshold_is_prop) {
  .Call(`_cheapr_cpp_matrix_missing_row`, x, threshold, threshold_is_prop)
}

cpp_matrix_missing_col <- function(x, threshold, threshold_is_prop) {
  .Call(`_cheapr_cpp_matrix_missing_col`, x, threshold, threshold_is_prop)
}

cpp_count_val <- function(x, value, recursive) {
  .Call(`_cheapr_cpp_count_val`, x, value, recursive)
}

cpp_int_sequence <- function(size, from, by) {
  .Call(`_cheapr_cpp_int_sequence`, size, from, by)
}

cpp_dbl_sequence <- function(size, from, by) {
  .Call(`_cheapr_cpp_dbl_sequence`, size, from, by)
}

cpp_sequence <- function(size, from, by) {
  .Call(`_cheapr_cpp_sequence`, size, from, by)
}

cpp_window_sequence <- function(size, k, partial, ascending) {
  .Call(`_cheapr_cpp_window_sequence`, size, k, partial, ascending)
}

cpp_lag_sequence <- function(size, k, partial) {
  .Call(`_cheapr_cpp_lag_sequence`, size, k, partial)
}

cpp_lead_sequence <- function(size, k, partial) {
  .Call(`_cheapr_cpp_lead_sequence`, size, k, partial)
}

cpp_sequence_id <- function(size) {
  .Call(`_cheapr_cpp_sequence_id`, size)
}

cpp_set_abs <- function(x) {
  .Call(`_cheapr_cpp_set_abs`, x)
}

cpp_set_floor <- function(x) {
  .Call(`_cheapr_cpp_set_floor`, x)
}

cpp_set_ceiling <- function(x) {
  .Call(`_cheapr_cpp_set_ceiling`, x)
}

cpp_set_trunc <- function(x) {
  .Call(`_cheapr_cpp_set_trunc`, x)
}

cpp_set_change_sign <- function(x) {
  .Call(`_cheapr_cpp_set_change_sign`, x)
}

cpp_set_exp <- function(x) {
  .Call(`_cheapr_cpp_set_exp`, x)
}

cpp_set_sqrt <- function(x) {
  .Call(`_cheapr_cpp_set_sqrt`, x)
}

cpp_set_add <- function(x, y) {
  .Call(`_cheapr_cpp_set_add`, x, y)
}

cpp_set_subtract <- function(x, y) {
  .Call(`_cheapr_cpp_set_subtract`, x, y)
}

cpp_set_multiply <- function(x, y) {
  .Call(`_cheapr_cpp_set_multiply`, x, y)
}

cpp_set_divide <- function(x, y) {
  .Call(`_cheapr_cpp_set_divide`, x, y)
}

cpp_set_pow <- function(x, y) {
  .Call(`_cheapr_cpp_set_pow`, x, y)
}

cpp_set_log <- function(x, base) {
  .Call(`_cheapr_cpp_set_log`, x, base)
}

cpp_set_round <- function(x, digits) {
  .Call(`_cheapr_cpp_set_round`, x, digits)
}

is_alt_compact_seq <- function(x) {
  .Call(`_cheapr_is_alt_compact_seq`, x)
}

alt_compact_seq_data <- function(x) {
  .Call(`_cheapr_alt_compact_seq_data`, x)
}

cpp_sset_range <- function(x, from, to, by) {
  .Call(`_cheapr_cpp_sset_range`, x, from, to, by)
}

cpp_sset_df <- function(x, indices) {
  .Call(`_cheapr_cpp_sset_df`, x, indices)
}

cpp_vec_length <- function(x) {
  .Call(`_cheapr_cpp_vec_length`, x)
}

cpp_r_unnested_length <- function(x) {
  .Call(`_cheapr_cpp_r_unnested_length`, x)
}

cpp_lengths <- function(x) {
  .Call(`_cheapr_cpp_lengths`, x)
}

cpp_new_list <- function(size, default_value) {
  .Call(`_cheapr_cpp_new_list`, size, default_value)
}

cpp_drop_null <- function(l, always_shallow_copy) {
  .Call(`_cheapr_cpp_drop_null`, l, always_shallow_copy)
}

cpp_list_as_df <- function(x) {
  .Call(`_cheapr_cpp_list_as_df`, x)
}

r_copy <- function(x) {
  .Call(`_cheapr_r_copy`, x)
}

cpp_which_ <- function(x, invert) {
  .Call(`_cheapr_cpp_which_`, x, invert)
}

cpp_which_val <- function(x, value, invert) {
  .Call(`_cheapr_cpp_which_val`, x, value, invert)
}
